### ISSUE TITLE
Workout getGPX method return warnings and fatal error.

### ISSUE THREAD

**Issue by lamp5** [fabulator/endomondo-workouts#2]
Hi. I started working with your package. When I want to get workout GPX, I can see warnings and fatal error.

> Warning: SimpleXMLElement::__construct(): Entity: line 1: parser error : attributes construct error in C:\xampp\htdocs\endo\vendor\fabulator\endomondo-workouts\lib\Fabulator\Endomondo\Workout.php on line 578
> 
> Warning: SimpleXMLElement::__construct(): <gpx xmlns="http://www.topografix.com/GPX/1/1"xmlns:gpxtpx="http://www.garmin.co in C:\xampp\htdocs\endo\vendor\fabulator\endomondo-workouts\lib\Fabulator\Endomondo\Workout.php on line 578
> 
> Warning: SimpleXMLElement::__construct(): ^ in C:\xampp\htdocs\endo\vendor\fabulator\endomondo-workouts\lib\Fabulator\Endomondo\Workout.php on line 578
> 
> Warning: SimpleXMLElement::__construct(): Entity: line 1: parser error : Couldn't find end of Start Tag gpx line 1 in C:\xampp\htdocs\endo\vendor\fabulator\endomondo-workouts\lib\Fabulator\Endomondo\Workout.php on line 578
> 
> Warning: SimpleXMLElement::__construct(): <gpx xmlns="http://www.topografix.com/GPX/1/1"xmlns:gpxtpx="http://www.garmin.co in C:\xampp\htdocs\endo\vendor\fabulator\endomondo-workouts\lib\Fabulator\Endomondo\Workout.php on line 578
> 
> Warning: SimpleXMLElement::__construct(): ^ in C:\xampp\htdocs\endo\vendor\fabulator\endomondo-workouts\lib\Fabulator\Endomondo\Workout.php on line 578
> 
> Warning: SimpleXMLElement::__construct(): Entity: line 1: parser error : Extra content at the end of the document in C:\xampp\htdocs\endo\vendor\fabulator\endomondo-workouts\lib\Fabulator\Endomondo\Workout.php on line 578
> 
> Warning: SimpleXMLElement::__construct(): <gpx xmlns="http://www.topografix.com/GPX/1/1"xmlns:gpxtpx="http://www.garmin.co in C:\xampp\htdocs\endo\vendor\fabulator\endomondo-workouts\lib\Fabulator\Endomondo\Workout.php on line 578
> 
> Warning: SimpleXMLElement::__construct(): ^ in C:\xampp\htdocs\endo\vendor\fabulator\endomondo-workouts\lib\Fabulator\Endomondo\Workout.php on line 578
> 
> Fatal error: Uncaught Exception: String could not be parsed as XML in C:\xampp\htdocs\endo\vendor\fabulator\endomondo-workouts\lib\Fabulator\Endomondo\Workout.php:578 Stack trace: #0 C:\xampp\htdocs\endo\vendor\fabulator\endomondo-workouts\lib\Fabulator\Endomondo\Workout.php(578): SimpleXMLElement->__construct('<gpx xmlns="htt...') #1 C:\xampp\htdocs\endo\index.php(13): Fabulator\Endomondo\Workout->getGPX() #2 {main} thrown in C:\xampp\htdocs\endo\vendor\fabulator\endomondo-workouts\lib\Fabulator\Endomondo\Workout.php on line 578

**Comment by fabulator** [comment]
That it weird. It seems that problem is in following code:
```
$xml = new \SimpleXMLElement(
            '<gpx xmlns="http://www.topografix.com/GPX/1/1"'
            . 'xmlns:gpxtpx="http://www.garmin.com/xmlschemas/TrackPointExtension/v1"'
            . '/>'
        );
```

But when I try it in http://sandbox.onlinephpfunctions.com/ it works OK. It complains that it missing end of gpx tag. It could be problem of specific PHP version or settings.

**Comment by lamp5** [comment]
I tested it on php 7.2. Now I know where is a problem.
`$xml = new \SimpleXMLElement(
            '<gpx xmlns="http://www.topografix.com/GPX/1/1" '
            . 'xmlns:gpxtpx="http://www.garmin.com/xmlschemas/TrackPointExtension/v1" '
            . '/>'
        );`
You forgot about spaces on the end of each line.

**Comment by fabulator** [comment]
I added spaces to source code.
